name: CI/CD pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and Push Docker image to Repository
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/demo-cicd:latest

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: dev

    steps:
      - name: Dev pr deploy
        run: echo "Dev environment par deploy ho gya!"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod

    steps:
      - name: Prod par deploy
        run: echo "Prod environment par deploy ho gya!"


